define({
  ru: true,
  de: true,
  es: true,
  lv: true,
  root: {
    MetaMain: 'Agent.ru provides online sale of tickets, train tickets and hotel accommodation. For each service available an advance reservation, which means to buy airline tickets, train tickets and accommodation online is even easier than before. We offer the lowest available price at the moment, so we have always cheap.',
    MetaEticket: 'Agent.ru is one of the first websites in Russia to offer electronic tickets for flights by Russian airlines. An e-ticket is an electronic form of an airline or train ticket that is proposed instead of a conventional paper ticket. What are the benefits of an electronic airline ticket?',
    MetaPointsOfSale: 'Agent.ru cooperates with over 100 sales points all over Russia. Airline tickets sell at those points at the same prices as the prices you see at Agent.ru. Book your airline tickets on our site and buy them at the sales point which is the closest to you!',
    MetaFlightStats: 'The Agent.ru airport board displays information about the status of each flight of Aeroflot, S7 (Siberia), Transaero, GTK Russia, UTair, and other airlines, arriving to and departing from Vnukovo, Domodedovo, Sheremetyevo 1 and 2, Pulkovo 1 and 2, and other airports of Russia and the world.',
    MetaAll: 'Agent.ru offers you the opportunity to book airline tickets online. You can book ordinary paper tickets or e-tickets. You can then get your tickets at any of our sales points, by email, or by courier.',
    ServerError: 'Server error! Reload the page and try again.',
    LoadingMessage: 'Loading...',
    BookingMessage: 'Processing your order...',
    InvalidMessage: 'Invalid field',
    EmailMessage: 'This field must contain an email address',
    NameMessage: 'The field may only contain Russian letters and hyphens',
    FullNameMessage: 'The field may only contain Russian letters, spaces, and hyphens',
    RusEngNameMessage: 'This field could contain only russian and english letters and hyphens',
    EngNameMessage: 'The field may only contain English letters and hyphens',
    AgeMessage: 'Specify the number of full years (18+)',
    PhoneMessage: 'Enter a country code (7 for Russia), operator/city code and phone number as one number (without spaces or other separators)',
    FlightMessage: 'Flight number looks something like this — AV123.',
    MinLengthMessage: 'The minimum number of characters in this field: #',
    NotBlankMessage: 'Please, fill in this field',
    PnrMessage: 'An order number may only include numerals and English letters',
    OrderNumberMessage: 'An order number may only include numerals, english letters, and hyphens',
    PassengersCountMessage: 'Total number of passengers must not exceed #',
    SeatsCountMessage: 'Total number of seats per order must not exceed #',
    PassengerMessage: 'Please, enter data of the passenger',
    DepartureDateMessage: 'Departure must not be earlier than previous one',
    MustAgreeMessage: 'To proceed with your booking you must agree to these terms',
    RemoveFromList: 'Remove from list',
    Yes: 'Yes',
    No: 'No',
    Cancel: 'Cancel',
    Error: 'Error',
    DuplicationPoint: 'Apparently you are attempting to book a round-the-world trip. Unfortunately such trips are not yet available, please choose a different destination :)',
    Input: 'Input',
    firstName: 'first name',
    middleName: 'middle name',
    lastName: 'last name',
    serialAndNumber: 'series and number',
    date: 'date',
    asDate: 'dd.mm.yyyy',
    numberOfBonusCard: '{0} bonus card number, if exists',
    DoublePerson: 'Last names and first names must not be equal',
    DateDoesNotCorrespond: "Entered date doesn't match to the passenger's category<br/>or the selected document",
    DocumentMustBeValid: 'Document must be valid<br/>for the entire trip',
    ForeignPassportMustBeValid: 'Foreign passport must be valid<br/>within six months after the trip',
    "Agent.ru": 'Agent.ru',
    "Agent.lv": 'Agent.lv',
    Personal: 'Personal page',
    MyOrders: 'My Orders',
    Registration: 'Registration',
    Logout: 'Log out',
    SupportService: 'Support service',
    AroundSupport: 'Works around the clock',
    OfficeHours: 'Open from 8:00 to 21:00 seven days a week',
    ElectronicMail: 'Email',
    AviaTickets: 'Airline tickets',
    TrainTickets: 'Train tickets',
    Hotels: 'Hotels',
    HotelsBooking: 'Hotel reservations',
    Booking: 'Booking',
    AirportTable: 'Airport board',
    Help: 'Help',
    Slogan: 'Agent.ru – selling and booking tickets from major airline companies.',
    FooterSlogan: '&copy; JSC &ldquo;AGENT.RU&rdquo; &mdash;<br/><a href="/en/">book and purchase airline tickets online</a>, 2006&ndash;2013.',
    AnonymousCopyright: 'Ticketing service is provided by <a class="show" target="_blank" href="http://www.agent.ru/"><nobr>JSC &ldquo;AGENT.RU&rdquo;</nobr></a>',
    AllRightsReserved: 'All rights reserved',
    Tel: 'Phone',
    News: 'News',
    About: 'About',
    ToPartners: 'For partners',
    PartnershipBonusPlan: 'Reward system',
    PartnershipAdvantages: 'Our advantages',
    PartnershipContracts: 'Contract templates',
    PartnershipAircompanies: 'For aircompanies',
    PartnershipTechnicalIssues: 'For technical specialists',
    ContactInfo: 'Contacts',
    Confidentiality: 'Privacy statement',
    SiteMap: 'Site map',
    NoscriptText: 'Warning! The Agent.ru website interface makes use of JavaScript.<br/>If you are reading this message, it means that your browser (or browser plugin), Internet connection or security settings prohibit to execute scripts on our web pages.<br/>Please, change your settings and refresh the page or contact your system administrator!',
    AviaticketsOverInternet: 'Plane tickets, train tickets, hotels. Sale of air tickets and train tickets, booking hotels. Order tickets by phone or delivery. We can find out the cost of air tickets and buy them online.',
    AviaBooking: 'Booking airline tickets',
    Any: 'Any',
    Morning: 'Morning',
    Day: 'Afternoon',
    Evening: 'Evening',
    Night: 'Night',
    One: 'One',
    Two: 'Two',
    Three: 'Three',
    Four: 'Four',
    Five: 'Five',
    Six: 'Six',
    CityNotFound: 'City not found',
    AirportNotFound: 'Airport not found',
    FlightPointNotFound: 'Location not found',
    StationNotFound: 'Station not found',
    From: 'From',
    To: 'To',
    andReturn: 'and back',
    ForwardDepartureDate: 'Date of original departure',
    ReturnDepartureDate: 'Date of return departure',
    ForwardDeparture: 'Original departure',
    ReturnDeparture: 'Return departure',
    Time: 'Time',
    PassengersCount: 'Passenger count',
    Adults: 'Adults',
    FindFlights: 'Find flights',
    AdvancedSearch: 'Advanced search',
    AllPromoActions: 'All promotions',
    ElectronicTicketsOfDifferentAirlines: 'Airline e-tickets',
    FullListOfAircompanies: 'Full list of airlines',
    ETicketsOfAircompanies: 'E-tickets from airlines: Aeroflot, S7 Airlines, Transaero, UTair, GTK Russia (Pulkovo), Ural Airlines, Austrian Airlines, Sky Express, Vladivostok Avia, AeroSvit, etc.',
    FlightStatus: 'Flight status',
    PaymentOfEtickets: 'All ways to pay',
    ByBankCard: 'By a bank card',
    ByAmExCard: 'By an American Express',
    InEurosetShop: 'At Euroset offices',
    ByYandexMoney: 'With Yandex.Money',
    UsingWebMoney: 'With WebMoney',
    InQiwiTerminals: 'With QIWI',
    ByAlfa: 'With Alfa-Click',
    FlightNumber: 'Flight number',
    forExample: 'for example',
    'or': 'or',
    Find: 'Find',
    ArchiveOfNews: 'News archive',
    AboutSite: 'About this site',
    AboutSiteText: '<p>Purchase plane or&nbsp;train tickets, book a&nbsp;hotel room, and rent a&nbsp;car&nbsp;&mdash; Agent.ru is&nbsp;where independent travelers go&nbsp;for all their travel needs.</p><p><a href="/en/booking/">Making flight reservations</a> is&nbsp;very easy: specify the departure and destination points, the dates you need, and your requirements, and Agent.ru will provide all available flight options. You, then, simply make your choice and pay for the <a href="/en/help/eticket/">electronic ticket</a>: you can do&nbsp;this using your bank card or&nbsp;through an&nbsp;electronic wallet (Yandex.Money, WebMoney or&nbsp;QIWI Wallet)&nbsp;&mdash; or&nbsp;pay in&nbsp;cash at&nbsp;any Euroset office. Your <nobr><a href="/en/help/eticket/#eticket-route-ticket">itinerary-receipt</a></nobr> will arrive in&nbsp;your <nobr>in-box</nobr> as&nbsp;soon as&nbsp;your payment is&nbsp;processed.</p><p>If&nbsp;you have any questions, refer to&nbsp;the <a href="/en/help/reservation/"><nobr>step-by-step</nobr> instructions</a> or&nbsp;contact our 24/7 customer support service&nbsp;&mdash; our operators will be&nbsp;glad to&nbsp;assist you.</p><p>Bon voyage!</p>',
    OnOurFlightTable: 'Our site provides information about the <a href="/en/flight-stats/">status of flights</a> of different airlines arriving to and departing from Vnukovo, Domodedovo, Sheremetyevo B&nbsp;(1), C, F&nbsp;(2) and the new terminals D and E, Pulkovo, as well as from other Russian airports. We are keeping track of changes in the schedule, flight cancellations and delays, and do our best to offer up-to-the-minute information.',
    OrderStatus: 'Order status',
    CheckStatus: 'Check',
    SearchOptimization: 'Search optimization',
    sitePromotion: 'site promotion',
    OGRN: 'OGRN 1057749370304',
    "12MOK": 'Certificate of accreditation in the TCH № D-0422 (12MOK)',
    YandexMoney: 'Yandex.Money',
    Contacts: 'Contacts',
    ChooseLanguage: 'Choose the language',
    ForthAndBack: 'Return flight',
    SimpleRoute: 'Simple route',
    ComplexRoute: 'Complex route',
    SimpleRouteTitle: 'Search for one-way flights or round trip',
    ComplexRouteTitle: 'Search the compound route with multiple flights',
    FlightSearch: 'Flight search',
    AnyF: 'Any',
    Economic: 'Economy',
    Business: 'Business',
    First: 'First',
    Important: 'Important',
    ImportantlyBlockFirst: 'If you need to&nbsp;buy tickets for more than 6&nbsp;passengers, please make multiple bookings.</p><p>Age of passengers is calculated at the time of departure of the last flight for the route.',
    IfYouBookRoundTrip: 'Try booking two separate tickets<br/>for both flight directions.',
    ChooseAnotherDate: 'Choose another date from the schedule',
    notMoreThan6: 'at most 6',
    From2To11: '2&ndash;11 years',
    Under2YearsWithoutSeat: '0&ndash;2 years, no seat',
    Under2YearsWithSeat: '0&ndash;2 years, with a seat',
    Under2Years: '0&ndash;2 years',
    Class: 'Class',
    Aircompany: 'Airline',
    aircompany: 'airline',
    IfYouAreSure: 'If you are sure there are such flights, try changing the number of passengers:<br/>the booking system is searching for all the tickets at the same price, but perhaps there are not enough tickets for everyone.',
    Preferencies: 'Preferences',
    steps: 'steps',
    NoAdultsHint: 'Ability to&nbsp;book a&nbsp;ticket for a&nbsp;child alone is&nbsp;available only with prior booking tickets<br/>for an&nbsp;adult passenger on&nbsp;the site Agent.ru.<br />Please note, that not all airlines offer this option.',
    AircompanyNotFound: 'Aircompany not found',
    IfYouChangeAircompany: 'Available on select No flights of the airline, try to choose another airline.',
    ShowLowcost: 'Show <nobr>low-cost</nobr> carriers',
    notShowLowcost: "don't show <nobr>low-cost</nobr> carriers",
    LowCostCarrier: 'Low-cost carrier',
    MessageForClass: 'Please note that some airlines have special seat arrangements on their aircraft which differ from Russian standards. Depending on the aircraft type, business class seats may be replaced with economy seats with extra comfort options.',
    Searching: 'It won’t take long!',
    PleaseWaitWhileSearching: 'Please wait, we are looking for your flight options…',
    PleaseWaitWhileSearchingText: 'The search will take no longer than a minute. Don’t close this window.',
    Alliance: 'Alliance',
    alliance: 'alliance',
    IfYouChangeAilliance: 'There are probably no available flights operated by airlines of the chosen alliance, please choose a different alliance or clear this field',
    PleaseWaitAeroexpress: '<p>Please wait, we are processing your search request...</p><p>You are being redirected to the official partner of Aeroexpress <a href="http://www.agent.ru/en/">Agent.ru</a></p>',
    forPassenger: 'for 1 passenger',
    forPassengers: 'for {0} passengers',
    SortBy: 'Sort the list. Hold SHIFT for multiple-column sorting.',
    ChooseCurrency: 'Choose the currency',
    ChoiceOfFlights: 'Choose a flight',
    ByCash: 'In cash',
    ByAgency: 'Agency',
    FromDeposit: 'From a deposit',
    Passengers: 'Passengers',
    adults: 'adults',
    under2YearsWithoutSeat: 'under 2 years of age, no seat',
    under2YearsWithSeat: 'under 2 years of age, with seats',
    ofChildren: 'children',
    ofChildrenWithoutSeat: 'children under 2 years of age, no seat',
    ofChildrenWithSeat: 'children under 2 years of age, with seats',
    "class": 'class',
    None: 'None',
    AnyM: 'Any',
    Route: 'Route',
    TransportBy: 'Transfer by the airline company',
    ShowFlightDetailedInfo: 'Show detailed information about the flights and payment types',
    Arcmpn: 'Airline',
    AirFlight: 'Flight',
    localTime: 'local time',
    Flight: 'Flight',
    flight: 'flight',
    DestinationsAndDates: 'Destinations and dates',
    ofFlight: 'of flight',
    ofFlights: 'of flights',
    variant: 'variant',
    ofVariant: 'variants',
    ofVariants: 'variants',
    FlightTime: 'Duration',
    h: 'h',
    min: 'm',
    PlaneType: 'Aircraft',
    planeType: 'aircraft',
    Change: 'Connection',
    TimeBetweenFlights: 'Connection time',
    ActualCarrier: 'Operated by',
    actualCarrier: 'operated by',
    TotalTravelTime: 'Total travel time',
    NextDay: 'next day',
    Connections: 'Connections',
    connections: 'connections',
    changes: 'connections',
    withChange: 'with connection',
    landings: 'stops',
    withLanding: 'with stop',
    rub: 'RUB',
    choose: 'select',
    AllPlacesExists: 'There are tickets for the specified number of passengers for all the specified flights. The price is the total for all the passengers specified and includes the fare, the airline fee, and the Agent.ru fee.',
    BookingParams: 'Booking parameters',
    ReturnToFlightSearch: 'Back to flight parameters',
    DepartureTime: 'Departure time',
    ArrivalTime: 'Arrival time',
    DepartureAirport: 'Airport of departure',
    ArrivalAirport: 'Airport of arrival',
    withoutChanges: 'non-stop',
    WithoutChanges: 'Non-stop',
    Departure: 'Departure',
    Arrival: 'Arrival',
    ToPay: 'To pay',
    TotalCost: 'Total cost',
    allFeesIncluded: 'all fees included',
    FlightsNotFound: "We couldn't find any flights matching your search criteria. Please try searching again with different parameters.",
    FlightsNotFoundGotoSchedule: 'Unfortunately there are no&nbsp;flights or&nbsp;no&nbsp;available tickets for the flights matching your request. Have a look at flight schedule on the route',
    orTryToChange: ' or try to make the search criteria less restrictive, changing it according to the recommendations below.',
    FlightsStateNotFound: "We couldn't find any flights matching your search criteria. There might not be any data available for one of the airports you've entered.<br/>Please try searching again with different parameters.",
    Close: 'Close',
    ShareLink: 'Share the link',
    SearchLink: 'Link to current search request',
    WaitWeAreCheckingAvailability: 'Waiting for confirmation from the airline',
    CancelChoice: 'Cancel choice',
    RefreshSearchResults: 'Refresh search results',
    CouldNotConfirmBookingPossibility: 'Unfortunately, the airline does not confirm the possibility to book the selected flight variant',
    NoTickets: 'Not available',
    AlreadyDeparted: 'Departed',
    OtherFlightDays: 'Try other dates',
    FlightsClosestDates: 'Flights on the closest dates',
    CheckTooManyPassengers: 'Unfortunately, you chose does not allow the airline ticketing more than 3 passengers.<br/> Please <a class="black" href="/en/booking/">take a few separate orders</a> with fewer passengers, or choose another airline.',
    DetailedInfo: 'Choice confirmation',
    LoginError: 'You have entered a wrong email address or password.<br/>Please, make sure the Caps Lock key is not pressed<br/> or use the password reminder feature.',
    ReturnToChoiceOfFlights: 'Back to choosing flights.',
    YourChoice: 'Your choice',
    ForwardFlight: 'Departure flight',
    ReturnFlight: 'Return flight',
    ShowTerms: 'Show the terms of exchange and refund of these tickets',
    AcceptTheFact1: 'Total payment amount depends on chosen payment method. You will be able to choose one upon completing your order.',
    AcceptTheFact2: 'We want you to understand that due to the operation specifics of booking systems the specified price of an airline ticket is not guaranteed until its issuance.',
    IAgree: 'I agree with',
    NextToPassengersData: 'Next: passenger data',
    FareRules: 'Fare application conditions',
    LowCostMessage: 'Low-cost carriers (<img class="lowcost" src="/media/img/icons/flight-forward-red.png" />) may not include meals and drinks aboard in the total price of your ticket. Some limitations may also be&nbsp;imposed on&nbsp;baggage transportation. To&nbsp;avoid conflicts at&nbsp;the airport please review the conditions of&nbsp;baggage and hand luggage transportation of&nbsp;the aircompany you have selected before flight.',
    lowCostRestrictions: 'restrictions of low-cost carriers',
    LowCostRestrictions: 'Restrictions of low-cost carriers',
    Total: 'Total',
    PriceIncludes: 'Price includes',
    ChoosePaymentMethod: 'Choose the preferred method of payment',
    OtherPaymentWays: 'Other payment ways',
    Cost: 'Cost',
    ChoiceLink: 'Link to this variant',
    TipOver15000QiwiEuroset: 'According to&nbsp;Federal Law &#8470;&nbsp;103&nbsp;as of&nbsp;January 1st 2010 the maximum amount of&nbsp;payments accepted at&nbsp;Euroset offices or&nbsp;using the QIWI Wallet may not exceed 14,999&nbsp;rubles. Please use a&nbsp;different payment method or&nbsp;create several separate orders so&nbsp;that the totals for each order would not exceed the indicated amount.',
    Customer: 'Customer',
    adult: 'adult',
    child: 'child',
    infantWithoutSeat: 'child under 2 years of age, no seat',
    infantWithSeat: 'child under 2 years of age, with a seat',
    FillPassengerData: 'Enter data for passenger No.',
    AddFromOrganizer: 'Add from the organizer',
    ChooseCountry: 'Choose a country',
    ComboDateNotValid: 'The date fields are filled in incorrectly.',
    FillField: 'Please, fill in this field.',
    forEx: 'e.g.',
    ForExample: 'For example',
    StartAgain: 'Start again',
    Document: 'Document',
    DocumentSerialAndNumber: 'Document number',
    Additional: 'Additionally',
    WeAreResponsible: 'We, Agent.ru, will be responsible for the correctness of passenger data and for notifying passengers about any problems with booking or payment in case of a flight cancellation or change of departure time. Therefore we need to have a means to contact you in urgent situations. Please, specify a phone number we may use for such purposes:',
    ContactPhone: 'Contact phone',
    ContactPhoneRecipient: 'Contact phone recipient',
    EmailRecipient: 'E-mail recipient',
    GoToPreFinalConfirmation: 'Next: order confirmation',
    EnterPassengerData: 'Enter passenger data and a contact phone number',
    ChoosePassengerFromOrganizer: 'Choose a passenger in your organizer',
    ChoosePassenger: 'Choose a passenger',
    PassengerData: 'Passenger data',
    FillInMissingData: 'Fill in missing passenger data',
    PassengersData: 'Passengers data',
    ToChoosePassenger: 'Choose a passenger',
    EditAndSave: 'Edit and save',
    HowToTranslit: 'Take note that the language to enter the name and surname in is determined by the airline’s rules. If you don’t know how to write your name or surname in English letters, you can contact our support service or visit the website <a class="show" target="_blank" href="http://www.translit.ru">www.translit.ru</a>.',
    LastNameEng: 'Last name (in English letters)',
    FirstNameEng: 'First name (in English letters)',
    LastName: 'Last name',
    FirstName: 'First name',
    MiddleName: 'Middle name',
    LastNameRus: 'Last name (in Russian letters)',
    FirstNameRus: 'First name (in Russian letters)',
    MiddleNameRus: 'Middle name (in Russian letters)',
    FullName: 'Full name',
    Sex: 'Sex',
    male: 'male',
    female: 'female',
    BirthDate: 'Date of birth',
    Citizenship: 'Citizenship',
    SelectDocumentForFlight: 'Select a document for flight',
    ForBonusProgramParticipants: 'For bonus program members',
    BonusCardNumber: 'Bonus card number',
    SeriesAndNumber: 'Series and number',
    Number: 'Number',
    ExpirationDate: 'Expiration date',
    validity: 'validity',
    ValidUntil: 'Valid until',
    Save: 'Save',
    ImportantlyBlockFourth: '<li>To ensure flight security and in accordance with the regulations of the Russian Federation Ministry of Transport, full passport data (series, number, period of validity) must be specified for each passenger when booking airline tickets.</li><li>If you add passenger data from your organizer, make sure the data is up to date because changing passenger data in a ticket may require paying a fine.</li><li>Don’t be upset if you don’t have your foreign passport with you, although it is required for booking. Its number can sometimes be found on the last page of the Russian passport.</li><li>For flights using a foreign passport, a discrepancy of 3 letters is allowed between the spellings of the surname in the passport and in the airline ticket because the passport contains a French transcription whereas the ticket, an English one. Additionally, the first letters must coincide and the general pronunciation of the surname must be recognizable.</li><li>Take note that errors in the document number are not permitted and may entail a ticket reissue fine or a denial of air transfer. Make sure the information is up to date if you add passenger data from your organizer.</li><li>If you are in the process of changing your Russian passport or have lost it, you can fly using your foreign passport.</li><li>The document you use to book an airline ticket must be effective at the date of flight. If you book your ticket using one document but fly using another, be ready to answer airport security’s questions.</li>',
    AccompanyLastName: 'Accompany lastname',
    AccompanyHint: 'Name "passenger-leader" and the order number should be entered strictly in accordance with the data of your order, made on site Agent.ru. If the order was not made by Agent.ru, unfortunately we can not issue a separate order for the child.',
    AccompanyingAdults: 'Accompanying adults',
    AccompanyingAdultsText: '<p>According to airline requirements to registration of air tickets for children in the separate order it is necessary to specify number of the order of the accompanying adult passenger and a surname of "passenger-leader" from this order. We ask you to concern with understanding to that in case of an unaccordance of this information or, on the contrary, granting of false data we will be compelled to refuse air ticket registration. Also we&nbsp;recommend you contact the airline or&nbsp;go&nbsp;to&nbsp;our main office to&nbsp;confirm the information in&nbsp;your order also has information about the order given to&nbsp;a&nbsp;child.</p><p>Pay attention that if the child will follow one, air ticket purchase on a site Agent.ru is impossible, since it is necessary to coordinate possibility of it with an air carrier in advance. In the process of booking order information on the child will also be included in the order of the accompanying adult. In any case we recommend to you after completion of registration to contact our central office or the airline to confirm this.</p>',
    OrderNumberInAgent: 'Ordering in Agent.ru',
    OtherItineraryDateChild: 'According to the rules of the airline, if a child turns 12 years old during the trip, the adult fare must be applied to him.',
    OtherItineraryDateInfant: 'According to the rules of the airline, if an infant turns 2 years old during the trip, the child fare must be applied to him.',
    ChangePassport: 'The passenger turns {0} years old before the end of the trip.<br/>Choose another document for trip or get a new passport in advance.',
    savePhone: 'Replace the phone number in your account settings on this',
    AddExtraServices: 'Remember to add extra services<br/>to your order before confirming it',
    asInDocument: 'as in the document',
    russianLetters: 'in russian letters',
    englishLetters: 'in english letters',
    RailwayAdults: 'Adults',
    RailwayChilds: 'Children 5&ndash;10 years',
    RailwayInfants: 'Children under 5 years',
    AdultPassengers: 'Adults',
    ChildPassengers: 'Children 2&ndash;11 years',
    InfantPassengers: 'Children under 2 years',
    MailRegisterData: '<p>To complete your booking you need to create a new account or login with an existing one.<br/>Registered users receive a number of benefits:</p><ul class="dash"><li>A personal area with a list of previous orders</li><li>The ability to save passengers and bonus cards for future use</li><li>Delayed check out</li></ul>',
    LoggedText: "Welcome back, {0}, we're happy to see you again!",
    RegisteredText: 'You have been successfully registered at Agent.ru, thank you!<br/>Your account information has been sent to the specified email, so feel free to proceed with your booking.',
    LinkForChangePasswordAccept: 'A letter has been sent to the specified email address.<br/>To change your password, click the link in that letter.',
    PurchaseTravellingAbroadInsurance: 'Are your visa documents in&nbsp;order?<br />You can take care of&nbsp;your travel insurance needs when you purchase your ticket!',
    PurchaseTravelInsurance: 'Travelling in&nbsp;Russia?<br />Protect yourself and your luggage with an&nbsp;<nobr>in-flight</nobr> insurance!',
    InsuranceProvidedBy: 'Insurance services are provided by AlfaStrakhovanie PLC',
    BookingAndOrdering: 'Order confirmation',
    ReturnToChoiceOfPassengers: 'Back to passenger selection',
    Checkout: 'Confirm the order',
    AirlineFees: 'Airline’s fee',
    AirlineFeesInclude: 'The airline’s fee includes fuel, environmental, customs, airport and other charges depending on the conditions and rules of air transportation for the selected route.',
    Fare: 'Fare',
    AgentFees: 'Agent.ru fee',
    CodeWord: 'Secret code',
    toAirport: 'to {0} airport',
    fromAirport: 'from {0} airport',
    TravellingAbroadInsuranceMore: 'Insurance for traveling abroad is&nbsp;accepted by&nbsp;all visa centers and includes coverage for medical expenses (including emergency dental care) of&nbsp;up&nbsp;to&nbsp;EUR 50,000.',
    TravelInsuranceMore: 'Your <nobr>in-flight</nobr> insurance provides coverage of&nbsp;up&nbsp;to&nbsp;RUB 500,000 in&nbsp;the event of&nbsp;injuries or&nbsp;illnesses sustained during the flight and up&nbsp;to&nbsp;RUB 20,000 for lost or&nbsp;damaged baggage.',
    AddToOrder: 'Add to order',
    TicketsAreNotRequired: 'Tickets are not required for children under 5 years old',
    TimeTableIs: 'Airport board &#151; information about flights from Vnukovo, Domodedovo, Sheremetyevo B&nbsp;(1), C, F&nbsp;(2) and the new terminals D and E, from Pulkovo and other Russian airports.',
    DepartureAwaiting: 'Awaiting departure',
    FlightCancelled: 'Flight cancelled',
    DepartureDelayed: 'Departure delayed',
    Awaiting: 'Awaiting arrival',
    Arrived: 'Landed',
    AwaitingDelayed: 'Arrival delayed',
    Diverted: 'Flight diverted',
    until: 'till',
    validUntil: 'valid until',
    at: 'at',
    FillFromAndToFieldsOrFlightNumber: 'Please, either fill in the To and From fields or enter the flight number (you can do this together with specifying the place of departure or destination) and you will see all flights matching your criteria.',
    TimeTableContent: '<p>In this section you can find detailed information about regular flights taking off from Russian airports or arriving in them, namely: </p><ul class="dash"><li>scheduled departure and arrival times;</li> <li>changes in the schedule;</li><li>information about delays;</li><li>flight cancellations;</li><li>information about intermediate stops.</li></ul><p>Now you don’t have to search for the necessary flight at websites of different airlines and airports to find out where and when to meet your friends or from where your plane takes off. All the information you need about flights of all major Russian airline companies (Aeroflot, Siberia (S7), Transaero, UTair, Pulkovo, Domodedovo Airlines, KrasAir, Vim Airlines, etc) is available first-hand on our site.</p><p>Our data are updated via information feeds from airlines and airports. Data from major airports (such as Sheremetyevo B&nbsp;(1), C, F&nbsp;(2) and the new terminals D and E, Domodedovo, Vnukovo, Pulkovo, Koltsovo, etc) and from the above-mentioned airline companies come faster than from other sources, therefore flight information is updated in real time. Unfortunately, delays with information updates are possible for other airports and airlines.</p><p>If information about the flight you are interested in does not appear too long or you cannot find it on the board, contact the airport or airline for detailed information about its status.</p>',
    SearchResults: 'Search results',
    DepartureDate: 'Departure date',
    Status: 'Status',
    FlightsAndPrices: 'Flights and fares',
    CreatingOrder: 'Ordering',
    DifficultiesWithLogin: 'Login/password problems',
    QuestionOrder: 'Ordering related questions',
    GettingDocumentsConfirmingPayment: 'Acquiring documents for accounting department',
    ReturnEticket: 'Refunding an electronic airline ticket',
    IncorrectSiteWork: 'Improper website operation',
    SuggestionsForImprovingSitePerformance: 'Suggestions on how to improve our website and support service',
    IneedEnglishSpeakingAssistance: 'I need English-speaking assistance',
    OtherF: 'Other',
    Phone: 'Phone',
    Phones: 'Phones',
    InMoscow: 'In Moscow',
    ForMobileCallsFromRegionsOfRussia: 'For calls from mobile phones and Russian regions',
    OfficeAddress: 'Office address',
    OfficesAddress: 'Offices addresses',
    OfficeAerovokzalAddressDirect: 'JSC “AGENT.RU”<br />125167, Moscow, Leningradskiy prospekt 37/12, “НИЦ АСК” building, 5<sup>th</sup> floor',
    OfficeLeninskyAddressDirect: '<div style="padding: 10px 0;">JSC “MAVS”<br />117261, Moscow, Leninskiy prospekt, 72/2<br /><a href="mailto:leninskiy@agent.ru">leninskiy@agent.ru</a></div><div>Open on weekdays from 9:00 to 20:00, weekends from 10:00 to 18:00</div><div class="supportService2">Tickets</div><div class="contactsPhone">+7 (495) 797-20-95</div><div class="supportService2">Tours, hotels</div><div class="contactsPhone">+7 (495) 797-20-96</div>',
    FeedbackMessageAfterSend: '<p>Thank you! Your message (<b>{0}</b>) has been sent and the support service will contact you as soon as possible.</p><p>If you do not receive an answer for 24 hours, call us and inquire about the status of your message by telling the operator its number.</p>',
    PartnershipMessageAfterSend: '<p>Thank you! Your message (<b>{0}</b>) has been sent and we will contact you as soon as possible.</p>',
    SendAnotherMessage: 'Send one more message.',
    FieldsMarkedAreRequired: 'Please, note that the fields marked with an asterisk (<span class="red">*</span>) are mandatory.',
    IntroduceYourselfPlease: 'Introduce yourself, please.',
    EmailToSendResponse: 'Email address for the answer to be sent to',
    SelectSubjectMessage: 'Choose your topic',
    FlightsAndPricesTip: 'If you need information about ticket fares and availability, please use the search form.',
    CreatingOrderTip: 'If you have any questions about ordering or have encountered any difficulties, you can call our operators any time of the day using the Moscow phone number<nobr>+7 (495) 797-4-797</nobr> or <nobr>8-800-50-50-797</nobr> (free calls from mobile phones and Russian regions).',
    DifficultiesWithLoginTip: 'If your password doesn’t work, make sure you use the correct letter case and language.',
    QuestionOrderTip: 'If you have any questions about your order, you can call our operators any time of the day using the Moscow phone number<nobr>+7 (495) 797-4-797</nobr> or <nobr>8-800-50-50-797</nobr> (free calls from mobile phones and Russian regions).',
    IncorrectSiteWorkTip: 'If a Server Connection Failure error appears when you try to book your tickets, this is not the site’s but the booking system’s problem.',
    EnterOrderNumber: 'What is your order number?',
    TextMessage: 'Message text',
    receiveDocsCopy: 'Send a scanned copy by email to me.',
    receiveDocsOffice: 'I will take the documents myself at the office of Agent.ru (Moscow, Leningradskiy prospekt 37/12, “НИЦ АСК” building, 5<sup>th</sup> floor)',
    receiveDocsPost: 'Send the documents by registered letter to the following address<br/>(free of charge)',
    Index: 'Postal code',
    postPlace: 'Region, city',
    postRecipient: 'Name of the organization and/or recipient',
    postCopyRefund: 'A copy of a filled-in refund notification',
    postCopyPassport: 'A copy of a passenger identification document',
    postCopyEuroset: 'Other documents (e.g. a Euroset check)',
    postCopyOther: 'Other materials',
    clientSubject: 'Enter the topic of your message',
    clientFile: 'Attach a file to the letter',
    IWantToWork: 'I would like to work at Agent.ru',
    VacancyName: 'Position',
    postCV: 'CV',
    ApplyNow: 'Apply now',
    Feedback: 'Feedback',
    RegisterEmail: 'Email address specified during registration',
    Address: 'Address',
    SendMessage: 'Send message',
    Country: 'Country',
    CountryNotFound: 'Country not found',
    free: 'free',
    maxFileSize: 'maximum file size is 3Mb',
    forcedRefund: 'forced',
    voluntaryRefund: 'voluntary',
    ForcedRefund: 'Forced',
    VoluntaryRefund: 'Voluntary',
    TimeDifference: 'The time difference with Moscow',
    ofHours: 'часов',
    MoreOffices: '+50 retail offices',
    Portal20Offices: 'Tickets from Agent.ru can be purchased through our <nobr>off-line</nobr> retail partner&nbsp;&mdash; <noindex><a href="http://portal20.ru/" class="show" rel="nofollow" target="_blank">Portal&nbsp;2.0</a></noindex>',
    InformationOnSite: 'On-site information placement',
    OnlineBookingSystem: 'Online booking system',
    ExtractOfAirTicketsInYourCashDesks: 'Issuance of airline tickets booked online at your ticket offices',
    AdvertisingPlacing: 'Ad placements',
    AnyYourOffers: 'Any offers from you',
    PartnershipContent: '<p>We are interested in new contacts and collaboration efforts. We use every opportunity to establish long-term partner relationships. Right now, we are ready to offer the following services to you:</p><ul class="dash"><li>publication of information about your sales points on our site,</li><li>placement of special offers,</li><li>installation of an online booking system on your site,</li><li>issuance of airline tickets booked online at your ticket offices,</li><li>ad placements on our site and on airline ticket envelopes.</li></ul><p>The list above is far from full and we are working to extend it. Therefore, we are always ready to listen to your counterproposals. If you want to collaborate with us, call us by the Moscow phone number&nbsp;+7 (495) 797-4-797 or contact us via email using the form below.</p>',
    PartnershipContentContactUs: '<p>To join the Agent.ru partnership proram, <a href="/ru/partnership/#feedback">leave us a message</a>.</p>',
    SiteUrl: 'Website address',
    Region: 'Region',
    AboutContent: '<p>Started on July 1, 2006, the Agent.ru project offers the unique opportunity for users to book airline tickets online, without leaving their computers.</p><p>Featuring a user-friendly interface, a large database, multiple ways to pay for and receive airline tickets, and a 24-hour support service, Agent.ru is a true leader in <nobr>online booking</nobr>.</p><p>Agent.ru provides airline ticket agencies the unique opportunity to save their time and money on developing their own booking websites. Instead, they can become an Agent.ru partner and enjoy all the benefits.</p><p>Among the new features available on our site is the schedule of actual movement of aircraft. By selecting a flight and departure location, you can follow the status of that flight in real time.</p>',
    Archive: 'Archive',
    PromoActions: 'Promo events',
    ThereAreCurrently: 'In effect',
    ArchivePromoAction: 'Archive of promo events',
    NoActionsThisYear: 'No actions this year.',
    HowToBook: 'How to book?',
    DelayOrCancelFlight: 'If a flight is delayed or cancelled',
    LawsAndRules: 'Laws and regulations',
    PaymentAndDelivery: 'Payment of tickets',
    ByBankCardOnSite: 'By a bank card on the Agent.ru website',
    ByAmExCardOnSite: 'By an American Express on the Agent.ru website',
    ByCashInEuroset: 'By cash at Euroset',
    ByNonCash: 'Non-cash payment',
    RefundAndChange: 'Refund or exchange',
    OnewayFlights: 'International one-way transfers',
    CompulsoryInsurance: 'Compulsory liability insurance of the air carrier',
    OfertaText: 'Public offer to provide airline ticket booking, ordering, selling and other services on the Agent.ru website.',
    TransportationConditions: 'NSAV/TKP Air Transportation Agreement Conditions',
    TransportationConditionsIata: 'Conditions of contract and other important NOTICES (IATA)',
    EticketForm: 'E-ticket form',
    AmendmentsToOrder: 'Amendments to the Order of the Ministry of Transport of the Russian Federation dated November 8, 2006 № 134',
    ConfirmSpends: 'Confirmation of expenditures',
    AirCodex: 'Russian Federation Air Code',
    FZ314: 'Russian Federation Federal Law No.314-FZ from December 1, 2007',
    FZ331: 'Russian Federation Federal Law No.331-FZ from December 4, 2007',
    Prikaz82: 'Russian Federation Ministry of Transportation Order No.82 from June 28, 2007, Moscow',
    Prikaz155: 'Russian Federation Ministry of Transportation Order No.155 from September 25, 2008, Moscow',
    UniSomeConventionOld: 'Convention for Unification of Certain International Air Transportation Regulations.',
    UniSomeConventionRules: 'Protocol of Amendments to Convention for Unification of Certain International Air Transportation Regulations.',
    UniSomeConventionAdd: 'Addendum convention to the Warsaw convention for unification of certain international air transportation regulations concerning non-contractual carriers.',
    ChicagoConvention: 'Convention on International Civil Aviation (Chicago Convention)',
    UniSomeConvention: 'Convention for unification of certain international air transportation regulations.',
    ElectronicTicket: 'Obtaining and using of tickets',
    WhatIsEticket: 'What is an electronic ticket?',
    Faq: 'F.A.Q.',
    ChooseFlight: 'Choose a flight',
    Payment: 'Payment',
    Delivery: 'Delivery',
    Buyout: 'Purchasing',
    SiteWork: 'Operation of the agent.ru website',
    Ask: 'Ask a question',
    ToBook: 'Booking',
    Commons: 'General',
    CommonQuestions: 'Common questions',
    SearchingAndChoosingFlight: 'Search and choose flights',
    EnteringPassengersAndPlacingOrder: 'Enter passengers data and place an order',
    PaymentAndTicketing: 'Pay your order and get tickets',
    RefundExchangeTicket: 'Refund or exchange tickets',
    CommonQuestionsAdditionalServices: 'Common questions, additional services',
    Privacy: 'Security and privacy',
    Partners: 'Partners',
    Authorization: 'Authorization',
    IfNoLogin: 'If you don’t have a login and password, you should',
    register: 'register',
    YourEmail: 'Your email',
    YourLogin: 'Your login',
    Password: 'Password',
    Enter: 'Log in',
    IForgotMyPassword: 'Forgot my password',
    SalePoint: 'Sales office',
    ToContinue: '<p>To continue with the booking, you must log in.</p><p>If you are already registered, enter your email and password.</p>',
    IAmRegistred: 'I am registered',
    RegisterNow: 'Register now',
    Next: 'Next',
    Register: 'Register',
    PassNotMatch: 'Passwords do not match; make sure you type them in correctly.',
    FillRegisterData: 'Please, fill in the fields of this form; all of them are mandatory.<br/>Upon successful registration you will receive a confirmation to the specified email address.',
    RepeatPassword: 'Repeat your password',
    IWantSMS: 'I want to receive <nobr>SMS notifications</nobr> about the status of my orders.',
    IWantEmail: 'I want to receive company news, special event notifications and other useful information from Agent.ru to my email address (the frequency of the mailing is no more than once a week).',
    Email: 'Email',
    PersonalArea: 'Personal page',
    StateAnnuled: 'Annulled',
    StateCancelled: 'Cancelled',
    StateWaitingForPay: 'Awaiting payment',
    StatePrintedEticket: 'Issued',
    StatePaymentFail: 'Awaiting payment',
    StatePaymentError: 'Payment error',
    StateAssistRequired: 'Contact support',
    StateWaitingForFlightsConfirmation: 'Waiting for confirmation by aircompany',
    StateRefund: 'Refunded',
    StateUnknown: 'Contact support',
    StateTicketing: 'Ticketing',
    Orders: 'Orders',
    Date: 'Date',
    AllTime: 'All time',
    Week: 'Week',
    Month: 'Month',
    Year: 'Year',
    HalfAYear: 'Half-year',
    Price: 'Price',
    NoOrders: 'No orders',
    Period: 'Period',
    PlaceFirstOrder: "You don't have any orders yet. <a href='/en/booking/'>Make your first reservation</a>.",
    Order: 'Order',
    ReservationCode: 'Reservation code',
    Passengers: 'Passengers',
    PassengerCategoriesNotConfirmed: 'Unfortunately, the selected passenger categories are not confirmed by the airline in automatic mode. It means that they may refuse to register you for the flight even if you have proper airline tickets. Please, contact the airline {0} and tell them your order number {1}, lead passenger name {2} and the direction of your flight to make sure you can continue with the ordering of your tickets.<br/>Operators of our 24-hour support service cannot get such a confirmation instead of you but will gladly tell you the phone number of the airline you have selected so that you could call them yourself. Call <nobr>+7 (495) 797-4-797</nobr> or <nobr>8-800-50-50-797</nobr> (free calls from mobile phones and Russian regions).',
    IgnoreCategoryConfirmation: 'I contacted the airline {0} and got a confirmation of flight for my order {1}.',
    IgnoringCategoryConfirmation: 'Thank you! Your order now contains information that you have contacted the airline to confirm the passenger categories and received a positive answer.',
    SumToPay: 'To pay',
    days: 'days',
    day: 'day',
    d: 'd',
    year: 'year',
    Made: 'Made',
    CashPaymentText: 'You may pay the order at any of the points of sales.<br/>Tell a cashier the order number <b>{0}</b> and the last name of the passenger <b>{1}</b>.',
    EurosetPaymentText1: 'To make the payment at any <a href="http://map.euroset.ru/map.html" target="_blank" class="show">Euroset</a> office on the territory of Russia, you should print out the receipt with barcode and order total and show it to the manager.',
    EurosetPaymentText2: 'If you cannot print out the receipt, please write down the information necessary to pay for your order',
    EurosetNotEnoughTime: '<p>Unfortunately, payment in Euroset is impossible because of the short time limit of payment set by the airline for this booking. Please consider using any other available payment method.</p>',
    TipOver15000rub: '<p>In&nbsp;accordance with Federal law &#8470;&nbsp;103 from 1 January 2010 amount received in&nbsp;the offices of&nbsp;Euroset payments may not exceed <b>14,999 rubles</b>. Please use another method of&nbsp;payment or, if&nbsp;possible, make a&nbsp;few separate orders, so&nbsp;that the cost of&nbsp;each did not exceed the specified limits.</p>',
    HowToEnterPayment: 'Порядок ввода платежа',
    HowToEnterPaymentText: '1С Рарус > Сервисные операции > кнопка “Europlat” > Авиа, ж\д билеты > Авиабилеты (Агент.ру)',
    PaymentCodeNotObtained: '<p>Checkout with Euroset is unfortunately impossible at this moment due to technical reasons, please consider using any other available payment method. If you wish to make your payment through Euroset, please contact our <a href="/en/about/contacts/?#map">Customer support service</a> on the phone or use fill in <a href="/en/about/contacts/?#mail">the feedback form</a>.</p>',
    AccordingFederalLaw103: 'According to Federal Law No.103 from January 1, 2010, the payment total cannot exceed 14,999 rubles. If your order total is higher than that value, please, use another payment method.',
    InCaseOfPaymentProblems: 'If there are any payment related problems, please do not leave the office but call our support service at the 24-hour Moscow number <nobr>+7 (495) 797-4-797</nobr> or <nobr>8-800-50-50-797</nobr> (free calls from mobile phones and Russian regions). We will explain the cashier what to do.',
    PleaseMakeSure: 'Make sure the preliminary bill and the shop bill issued by the cashier contain brief information about your order.',
    PlasticPaymentText: 'To make the payment you will be directed to the payment system server using secure connection. From the moment you arrive at the payment page, you will have 15 minutes to make your payment. If the payment cannot be made for some reason, you cannot make another attempt until these 15 minutes have passed.',
    PaymentFooter: 'If this is the first time that you pay for airline tickets ordered through our website, please read the rules of <a href="/en/help/payment-and-delivery/" target="_blank" class="show">payment</a> and <a href="/en/help/refund/#how-to-refund-ticket" target="_blank" class="show">refunding</a> for airline tickets.',
    WebMoneyPayment: 'To make the payment you will be directed to the WebMoney payment system server using secure connection. From the moment you arrive at the payment page, you will have 15 minutes to make your payment. If the payment cannot be made for some reason, you cannot make another attempt until these 15 minutes have passed.',
    YandexPayment: 'To make the payment you will be directed to the Yandex.Money payment system server using secure connection. From the moment you arrive at the payment page, you will have 15 minutes to make your payment. If the payment cannot be made for some reason, you cannot make another attempt until these 15 minutes have passed.',
    YandexPaymentTip: 'If the payment total is higher than 14,999 rubles, you have to additionally <noindex><a href="http://money.yandex.ru/security/identification/" rel="nofollow" class="show" target="_blank">authenticate yourself in the Yandex.Money system</a></noindex>',
    QiwiPayment: 'To make the payment you need to login at the QIWI Wallet website or at any QIWI payment terminal, choose and pay the corresponding invoice from Agent.ru. You may find more information in the <a href="http://ishopnew.qiwi.ru/files/qiwi_instruction.html" rel="nofollow" class="show" target="_blank">instructions on the QIWI Wallet website</a>.',
    QiwiRestricted: '<p>К&nbsp;сожалению, этот заказ нельзя оплатить с&nbsp;помощью QIWI Кошелька, <nobr>т. к.</nobr> мы&nbsp;не&nbsp;смогли выставить счет на&nbsp;его оплату. Скорее всего, это произошло потому, что на&nbsp;указанный вами при создании заказа номер телефона не&nbsp;зарегистрирован QIWI Кошелек.</p><p>Что делать дальше:</p><ul class="dash"><li>если в&nbsp;будущем вы&nbsp;хотите оплачивать заказы с&nbsp;помощью QIWI Кошелька, необходимо зарегистрировать его <noindex><a href="https://w.qiwi.ru/orders.action" class="show" target="_blank" rel="nofollow">на&nbsp;сайте сервиса</a></noindex>;</li><li>чтобы оплатить заказ именно с&nbsp;помощью QIWI Кошелька, необходимо отменить этот заказ и&nbsp;сделать новый&nbsp;&mdash; только так мы&nbsp;сможем выставить вам счет на&nbsp;оплату.</li></ul><p>Если вы&nbsp;не&nbsp;хотите отменять заказ, пожалуйста, воспользуйтесь другим предлагаемым способом оплаты&nbsp;&mdash; например, заведите виртуальную банковскую карту <noindex><a href="https://w.qiwi.ru/visaFeature.action" class="show" target="_blank" rel="nofollow">QIWI Visa Virtual</a></noindex> и&nbsp;оплатите заказ по&nbsp;карте.</p><p>В&nbsp;случае, если QIWI Кошелек у&nbsp;вас есть, но&nbsp;вы&nbsp;все&nbsp;же читаете это сообщение, пожалуйста, помогите нам стать лучше и&nbsp;<a href="/en/about/contacts/?subj=error#mail">сообщите Службе поддержки о&nbsp;проблеме</a>.</p>',
    TipOver15000rubQiwi: '<p>В&nbsp;соответствии с&nbsp;Федеральным законом &#8470;&nbsp;103 с&nbsp;1 января 2010 года размер единовременного платежа с&nbsp;помощью QIWI Кошелька может составлять не&nbsp;более <b>14,999&nbsp;рублей</b>. Пожалуйста, воспользуйтесь другим способом оплаты или, при возможности, сделайте несколько отдельных заказов, таким образом, чтобы стоимость каждого не&nbsp;превышала указанного ограничения.</p>',
    AlfaPaymentText: 'Pay the invoice from Agent.ru in Alpha-Click.',
    TipSheremetyevo: 'Please, make sure beforehand with your airline or airport in what exactly Sheremetyevo terminal your flight is going to take off or arrive.',
    SuccessTip: 'Thank you for your payment. Your order is complete; the itinerary receipt has been sent to your email address.',
    YourOrderMustBePaidWithin: 'Your order has to be paid for within',
    TimelimitMightBeReduced: 'In some cases, especially if the time-limit is more than 24 hours, the airline may unilaterally reduce the term of payment and cancel the order, so we recommend you carry out its payment as soon as possible.',
    RailwayOrderMustBePaid: 'According to the rules of rail transport your order has to be paid within',
    InAdditionToYourOrder: 'In addition to your order you can',
    BookAHotel: 'Make an hotel reservation at the destination city for the duration of your stay',
    AllHotels: 'All hotel offers',
    ToPayOrder: 'Pay for the order',
    ToPayNow: 'Pay now',
    WaitPaymentLoad: 'Takes you to the payment system site...',
    YouMayClose: 'You may close this window.',
    PrintOrder: 'Print',
    Send: 'Send',
    EmailOrder: 'Send by e-mail',
    EmailOrderSuccess: 'Information about order sent to the email address.<br/>Want to send another letter?',
    EmailOrderFail: 'Unfortunately, we were unable to send a letter.<br/>Please try again or report the error to our support.',
    EmailOrderData: 'Send data about the order',
    SmsSentOrder: 'Send SMS with the payment code',
    SmsOrderSuccess: 'SMS with a code of payment has been sent',
    printReceipt: 'Print the receipt',
    ListOrders: 'List of orders',
    inMoscowTime: 'Moscow time',
    oneOfTheFollowingWays: 'in one of the following ways',
    TermsOfTheAirTransportation: 'Contract of Air Transportation Conditions',
    DocumentsForAccounting: 'Accounting documentation',
    RouteReceipt: 'Itinerary receipt',
    ofRouteReceipt: 'itinerary receipt',
    GettingRouteReceipt: 'Getting itinerary receipt',
    CancelOrder: 'Cancel your order',
    OrderCancellation: 'Cancel your order',
    CancelOrderConfirm: 'Do you really want to cancel your order?',
    ScanBarCode: 'Scan your barcode',
    OrEnterPaymentCode: 'OR enter your payment code',
    BriefOrdering: 'Order summary',
    OrderNumber: 'Order number',
    orderNumber: 'order number',
    PrintRouteTicket: 'Print the <noindex><a href="{0}" target="_blank" rel="nofollow" class="show">route-receipt</a></noindex>.',
    PrintRailwayTicket: 'Print the <noindex><a href="{0}" target="{1}" rel="nofollow" class="show">electronic ticket</a></noindex>.',
    ETicket: 'Electronic ticket',
    ConfirmationReceived: 'The payment system has submitted a confirmation. Your order is complete.',
    UnfortunatlyOrder: 'Unfortunately, your order cannot be made; it will be cancelled automatically. Please, try to make another order with different parameters (flight, date, airline, etc).',
    OrderWasNotPaid: 'The order has not been paid for. Try again or use another payment method.',
    PleaseWait: 'Please, wait until the payment is confirmed by the payment system and the itinerary receipt is created.',
    RouteTicketSabre: '<p>To&nbsp;obtain the itinerary receipt for a&nbsp;flight, go&nbsp;to&nbsp;the site reservation system Sabre <sup><small>&reg;</small></sup> Virtually There <sup><small>&reg;</small></sup>, specify the order number {0}, the passenger&rsquo;s surname and click on&nbsp;&ldquo;View Itinerary&rdquo;; then enter the email address provided during registration on Agent.ru, and again press the &ldquo;View Itinerary&rdquo;. You will see your itinerary receipt, which can be&nbsp;saved on&nbsp;your computer or&nbsp;send to&nbsp;any address using the links in&nbsp;the menu on&nbsp;the right.</p>',
    RouteTicketSirena: '<p>To&nbsp;obtain the itinerary receipt for a&nbsp;flight, go&nbsp;to&nbsp;the site reservation system <nobr>Sirena-Travel</nobr> <noindex><a class="hidden" href="http://www.myairlines.ru/pages/myOrder.jsf" target="_blank" rel="nofollow">MyAirlines</a></noindex>, specify the order number {0}, the passenger&rsquo;s surname and click on&nbsp;&ldquo;Show information&rdquo;. You will see your itinerary receipt, which can be&nbsp;saved on&nbsp;your computer or&nbsp;send to&nbsp;any address using the links in&nbsp;the menu on&nbsp;the right.</p>',
    RouteTicketLowfare: "<p>A link to your itinerary receipt and all the necessary instructions were sent by the aircompany to your e-mail address. If the e-mail delivery failed for some reason, please visit the aircompany's website and follow the instructions to retrieve your itinerary reciept. Please note that the process may vary depending on the aircompany. If you are experiencing difficulties retrieving your itinerary receipt, please contact our 24/7 Customer support service.</p>",
    RouteTicketAmadeus: '<p>To obtain the itinerary receipt for your flights you will be redirected to CheckMyTrip - the reservation system website. You will see your itinerary receipt, which can be saved to your computer, printed or sent to any e-mail address using the links at the top of the page.</p>',
    NeedToPrintRouteTicket: '<p>Itinerary receipt must be&nbsp;printed on&nbsp;an&nbsp;ordinary sheet of&nbsp;A4, and in&nbsp;any case carry for registration and control of&nbsp;the airport.</p>',
    NeedToPrintRouteTicketAex: 'p>Please print your itinerary receipt and Aeroexpress tickets on&nbsp;ordinary <nobr>A4-sized</nobr> sheets of&nbsp;paper and have them handy at&nbsp;the airport. You will be&nbsp;required to&nbsp;present these documents at&nbsp;the railway platform turnstiles, to&nbsp;a&nbsp;controller, and at&nbsp;the flight <nobr>check-in</nobr>.</p>',
    GetRouteTicketFromSupport: '<p>To&nbsp;obtain the itinerary receipt for a&nbsp;flight, please contact our 24/7 Customer support service.</p>',
    GetRouteTicket: '<p>Download your itinerary receipt using the link below.</p>',
    AwaitingAircompanyConfirmation: 'Your order is to be confirmed by the airline, which should take no more than 10 minutes. If it takes longer, we will additionally notify you by email that you can continue with your ordering.',
    TechnoWaitingPlastic: '<p>Payments by bank cards are not accepted due to technical reasons from &nbsp;<span class="technoWaitingStart"></span> till&nbsp;<span class="technoWaitingEnd"></span> Moscow time. Please, use another payment method or wait for <span class="technoWaitingTime"></span> minutes.</p><p>We are very sorry that you see this message but we hope for your understanding.</p>',
    TechnoWaitingYandex: '<p>Payments with Yandex.Money are not accepted due to technical reasons from &nbsp;<span class="technoWaitingStart"></span> till&nbsp;<span class="technoWaitingEnd"></span> Moscow time. Please, use another payment method or wait for <span class="technoWaitingTime"></span> minutes.</p><p>We are very sorry that you see this message but we hope for your understanding.</p>',
    TechnoWaitingWebMoney: '<p>Payments with WebMoney are not accepted due to technical reasons from &nbsp;<span class="technoWaitingStart"></span> till&nbsp;<span class="technoWaitingEnd"></span> Moscow time. Please, use another payment method or wait for <span class="technoWaitingTime"></span> minutes.</p><p>We are very sorry that you see this message but we hope for your understanding.</p>',
    TechnoWaitingQiwi: '<p>Payments with Qiwi are not accepted due to technical reasons from &nbsp;<span class="technoWaitingStart"></span> till&nbsp;<span class="technoWaitingEnd"></span> Moscow time. Please, use another payment method or wait for <span class="technoWaitingTime"></span> minutes.</p><p>We are very sorry that you see this message but we hope for your understanding.</p>',
    TechnoWaitingAlfa: '<p>Payments with Alfa-Click are not accepted due to technical reasons from &nbsp;<span class="technoWaitingStart"></span> till&nbsp;<span class="technoWaitingEnd"></span> Moscow time. Please, use another payment method or wait for <span class="technoWaitingTime"></span> minutes.</p><p>We are very sorry that you see this message but we hope for your understanding.</p>',
    ContinueOrdering: 'Continue with ordering',
    ReceiptIsOnly: '<b>This receipt is only intended to pay for your order.</b><br/>The itinerary receipt for your flight will be sent to the specified<br/>email address after the payment and the issuance of airline tickets.',
    YourOrderMustBePaidUntil: 'Your order must be paid for until',
    inAnyEurosetOffice: 'at any Euroset office on the territory of Russia',
    TimeLimitExpired: 'Time limit expired',
    TicketNumbers: 'Ticket numbers',
    Accompany: 'Accompany',
    LeadPassenger: 'Lead passenger',
    payByEuroset: "Your order has been paid in Euroset, so a document confirming the payment, <br /> a cashier's check issued by you to the cashier after the payment transaction in the passenger compartment connection",
    ChooseAGift: 'Choose a gift for every ticket purchased!',
    MoreAboutAction: 'Promo rules',
    ThankYouAction: 'Thank you, your application is accepted, and it means that your gift is already halfway to you.',
    AfishaFormTitle: 'Pledge successful and timely receipt of the desired gift - correctly typed the address for delivery. Please carefully fill in all fields of this form',
    GuideToAirfare: 'Guide to airfare',
    AfishaError: 'Oops! Sorry, unexpected error thrown. Please, contact our Support service.',
    AfishaPleaseSelect: 'Please select at least one guide!',
    SendGuideAddress: 'Address to send guide',
    CantFindOrder: 'No orders with such parameters',
    Paid: 'Paid',
    ToRefundTicket: 'Refund ticket',
    CanBeVoided: 'Void tickets',
    TicketWithElectronicalRegistration: 'Please print your e-ticket containing control and boarding coupons and a TCH e-document on ordinary sheets of A4 paper and have them ready when boarding the train.',
    TicketWithoutElectronicalRegistration: "Please print your e-ticket containing a control coupon and a TCH e-document on ordinary sheets of A4 paper.<br />Since you've chosen to buy a ticket without online check-in, you'll have to use these documents to obtain your boarding pass at an RZD ticketing desk or using a self-service terminal.",
    OtpWarning: 'Please note that by proceeding to checkout you confirm that all passenger and document data in the order is correct.',
    BonusCards: 'Bonus cards',
    AddBonusCard: 'Add a bonus card',
    BonusCard: 'Bonus card',
    BonusProgram: 'Bonus program',
    CardNumber: 'Card number',
    WannaDeleteBonusCard: 'Do you really want to delete this bonus card?',
    BonusCardRemoval: 'Delete bonus card',
    Passenger: 'Passenger',
    NoBonusCards: 'Bonus cards are not specified.',
    ChooseCity: 'Choose your city',
    ChooseBonusProgram: 'Choose your bonus program',
    DeliveryAddresses: 'Delivery addresses',
    AddDeliveryAddress: 'Add a new delivery address',
    WannaDeleteDeliveryAddress: 'Do you really want to delete this delivery address?',
    DeliveryAddress: 'Delivery address',
    NoDeliveryAddresses: 'Delivery addresses are not specified.',
    City: 'City',
    Directions: 'Directions',
    NoPassengers: 'No passengers specified',
    AddPassenger: 'Add a passenger',
    WannaDeletePassenger: 'Do you really want to delete this passenger?',
    PassengerRemoval: 'Delete passenger',
    PersonalData: 'Personal data',
    SaveChanges: 'Save the changes',
    FillFromPassengerData: "Fill in the form using one of your passengers' data",
    PasswordReset: 'Password recovery',
    EnterEmailToReset: 'A letter with a link to the password change page will be sent to the specified email address.<br/>If you do not remember the address you specified during registration, please contact our 24-hour support service and our operators will tell it to you.',
    SendMail: 'Send the letter',
    ChangePassword: 'Change the password',
    ChangingPassword: 'Changing the password',
    NewPassword: 'New password',
    ConfirmPassword: 'Confirm the password',
    SavePassword: 'Save the password',
    AccountSettings: 'Account settings',
    ChangeEmail: 'Change the email address',
    DeleteAccount: 'Delete account',
    DeleteAccountTip: 'To delete your account (including personal details, passengers in a notebook, information about the bonus maps and history of your orders), please press the big red button below',
    ConfirmDelete: 'After clicking on the "Delete all" account and all stored there information can not be restored - you sure you want to continue?',
    HasOpenOrdersNotDelete: 'Do you have unregistered orders - in order to continue the process of removing an account, please cancel or decorate. Thank you.',
    DeleteAttention: 'Note that a deleted account can not be restored',
    DeletePermanently: 'Delete permanently',
    DoNotDelete: 'Do not delete',
    NotPossibleToDelete: 'Not possible to delete an account',
    BackToOrders: 'Back to&nbsp;&ldquo;Orders&rdquo;',
    PasswordChanged: 'Your password was changed successfully',
    OldPassword: 'Old password',
    EmailChanged: 'Your email address has been changed successfully',
    EmailWillBeChanged: '<p>Your email address in the system will be changed.<br/>Do not forget that it is used as a user name when logging into the personal page.<br/>Press Yes to change the address or No to keep the old one.</p>',
    Popular: 'Popular',
    References: 'References',
    Countries: 'Countries',
    AllCountries: 'All countries',
    Cities: 'Cities',
    AllCities: 'All cities',
    Airports: 'Airports',
    AllAirports: 'All airports',
    AllAirportsInList: '(all airports)',
    Airport: 'Airport',
    Aircompanies: 'Aircompanies',
    AllAircompanies: 'All aircompanies',
    All: 'All',
    SearchInReferences: 'Search in references',
    Search: 'Search',
    CityName: 'City name',
    InternationalCityName: 'International city name',
    InnerCityCode: 'Inner city code',
    CityCodeIata: 'City code IATA',
    AirportName: 'Airport name',
    InnerCode: 'Inner code',
    CodeIATA: 'Code IATA',
    InternationalCountryName: 'International country name',
    InternationalName: 'International name',
    CompanyName: 'Company name',
    Site: 'Site',
    Information: 'Information',
    Logo: 'Logo',
    Latitude: 'Latitude',
    Longitude: 'Longitude',
    СurrentTime: 'Сurrent time',
    Capital: 'Capital',
    AircompanyOperatingTransport: 'Aircompany operating transportation in airport',
    DistanceToCenter: 'Distance to the center of city',
    km: 'km',
    Lions: 'Points of interest',
    Transport: 'Transport',
    TransportInCity: 'City public transport',
    AreaAndPopulationInCity: 'City area and population',
    TemperatureInCity: 'Temperature',
    UsefulInfo: 'Useful Info',
    Traffic: 'Passenger traffic, mm per year',
    calculationYear1: 'as of',
    calculationYear2: 'year',
    OfficialSite: 'Official site',
    HowToReachCity: 'How to get to the city from the airport',
    Briefly: 'Briefly',
    AreaSqm: 'Area, sq miles',
    PopulationMln: 'Population, mm',
    TimeUTC: 'Time, UTC',
    Sites: 'Sites',
    Climate: 'Climate',
    TemperatureCelcium: 'Temperature, °C',
    averageMaximumMinimum: 'average maximum / average minimum',
    winter: 'winter',
    spring: 'spring',
    summer: 'summer',
    autumn: 'autumn',
    NormRainfall: 'Precipitation norm, mm/month',
    Tourism: 'Tourism',
    Visa: 'Visa',
    OfficialLanguage: 'Official language',
    Currency: 'Currency',
    Schedule: 'Schedule',
    ScheduleCalendar: 'Schedule',
    ShowTheSchedule: 'Show the schedule',
    ScheduleFlights: 'Schedule of flights',
    ShowFlightSchedule: 'Show the flight schedule',
    FligthDays: 'Дни полётов',
    Terminal: 'Terminal',
    terminal: 'terminal',
    ShowSchedule: 'Show schedule',
    FindTickets: 'Find tickets',
    ReCaptchaTextLeft: '<h3>Instructions</h3><ul class="dash"><li>Please enter the words you see in the box, in order and separated by a space. Doing so helps prevent automated programs from abusing this service.</li><li>If you are not sure what the words are, either enter your best guess or click the button <img src="/media/img/buttons/refresh.png" alt="reload" /> next to the distorted words.</li></ul>',
    RecaptchaFoo: 'reCAPTCHA © 2013 Google',
    ReCaptchaTextRight: '<h3>Helping the World One Word at a Time</h3><p>By entering the words in the box, you are also helping to digitize texts that were written before the computer age. The words that you see were taken directly from old texts that are being scanned and stored in digital format in order to preserve them and make them more accessible to the world. Since some of the words in these texts are difficult for computers to process, we are using the results of your efforts to help decipher them.</p>',
    ReCaptchaPlayAgain: 'Play again',
    ReCaptchaCantHear: 'Download the MP3 audio',
    TypeinTwoWords: 'Write two words',
    TypeinWhatYouHear: 'Write what you hear',
    SwapImage: 'Replace the visual code on the audio track',
    SwapAudio: 'Replace the audio track on the visual code',
    ReCaptchaRefresh: 'Try again',
    BookingForAgency5: 'Guidelines for booking and sale of air transport for agencies (5 th edition)',
    NoData: 'No data',
    RefundStateCalculated: 'Calculated',
    RefundStateRejected: 'Rejected',
    RefundStateAwaiting: 'Awaiting',
    RefundStateInProcess: 'In process',
    RefundStateReadyToGiveCash: 'Ready to refund',
    RefundStateGivenCash: 'Refunded',
    RefundStateWaitingForAircompanyConfirmation: 'Waiting for confirmation',
    Ticket: 'Ticket',
    VoluntaryRefundType: 'Voluntary refund',
    ConstrainedRefundType: 'Involuntary refund',
    Reason: 'Reason',
    TicketCost: 'Ticket cost',
    Charges: 'Charges',
    RefundCharge: 'Refund charge',
    PercentRefundCharge: '{0}% fare deduction',
    EuroRefundCharge: '{0} EUR refund charge',
    UsdRefundCharge: '{0} USD refund charge',
    PercentPenalty: '{0}% fare penalty',
    EuroPenalty: '{0} EUR fare penalty',
    UsdPenalty: '{0} USD fare penalty',
    RefundFine: 'Refund fine',
    RefundFare: 'Fare of the used segments',
    RefundSum: 'Refund total',
    RefundTicket: 'Refund ticket',
    ToRefundTickets: 'Refund tickets',
    RussianPassport: 'Russian passport',
    RussianForeignPassport: 'Russian Foreign Passport',
    NationalityPassport: 'Other document',
    RussianBirthSertificate: 'Свидетельство о рождении',
    RefundCalculation: 'Расчёт денежных средств к возврату',
    IAgreeRefund: 'I agree with <a class="show" target="_blank" href="/en/help/refund/">terms of repayment</a>, and I understand that after posting this query on the selected flight to return the tickets is impossible.',
    SelectPassengersToRefund: 'For each passenger, select the flights, tickets for which you want to return',
    refundFullOrder: 'return the entire order all',
    EnterLastNumbersOfTicket: 'Enter last three digits of the number of',
    SelectRefundType: 'Choose the type of return',
    RefundType: 'Refund type',
    Refunds: 'Refunds',
    ForcedRefundInfo: 'Forced return can be issued only on these grounds and only with the permission Airlines',
    FlightCancelOrTransfer: 'Flight cancellation or transfer of flight',
    AttachFile: 'Attach file',
    TheDeathOfPassenger: 'The death of passenger',
    FlightDelay: 'Flight delay',
    ChangeCarrierRoute: 'Change in carrier route',
    LackOfSeatsInFlight: 'Lack of seats in the flight',
    FailureToProvideServiceOnClass: 'Failure to provide passenger service on the class specified on the ticket',
    FailureByCarrierFlightConnections: 'The failure by the carrier flight connections in the case when a single transport',
    DelayInAirportInspection: 'DelayInAirportInspection=Delay in airport inspection, if the result was not found banned substances or articles, and was issued the corresponding certificate',
    TerminationInitiatedByCarrier: 'Termination initiated by the carrier of the air transportation (except passenger violations of rules of conduct on board the aircraft)',
    WereThereAnyCommissionedPlaces: 'Were there any pre-commissioned places?',
    PleaseIndicateWhenAndWhere: 'Please indicate when and where you have taken place, and attach scanned documents',
    OtherIt: 'Other',
    RefundTickets: 'Refund tickets',
    FlightCancelOrTransfer: 'Flight cancellation or transfer of flight',
    Unspecified: 'Unspecified',
    SpecifyNumberOfTicketsFrom: 'Specify the number of tickets from',
    RefundSuccess: '<p>Thank you! Your refund request has been received and will be&nbsp;processed within 24&nbsp;hours. You may see the status of&nbsp;your request on&nbsp;the order details page in&nbsp;the &ldquo;Refunds&rdquo; section.</p><p>If&nbsp;necessary, our Customer support service operators will contact you for additional information or&nbsp;clarifications. Please understand that this may increase the time it&nbsp;takes to&nbsp;process your request.</p>',
    ToOrderCall: 'To order call',
    CallmeTime: 'Select time to call',
    CallmeSubjects: 'Choose the subject',
    CallRequestSuccess: 'We will call you back.',
    MoscowTime: 'Moscow time',
    TicketExchange: 'Ticket Exchange',
    CurrencyFootnote: 'Prices are displayed at the rate of the CBR at the time of viewing. Payment for orders may only be made in Russian rubles.',
    recordsNotFound: 'not found any record',
    Go: 'Go',
    Children5to7: 'Children 5&ndash;7 years',
    Aeroexpress: 'Aeroexpress',
    DoesNotMatter: 'Does not matter',
    SearchOptimization: 'Search engine optimization',
    websitePromotion: 'website promotion',
    gate: 'gate',
    airport: 'airport',
    time: 'time',
    notMoreThan4: 'at most 4 seats',
    ChildrenFrom5to10: '5&ndash;10 years',
    Under5Years: 'Under 5 years',
    withoutSeat: 'no seat',
    withSeat: 'with a seat',
    SearchOfJourneys: 'Search of journeys',
    ChoiceOfJourney: 'Choice of journey',
    ChoiceOfSeats: 'Choice of seats',
    TrainType: 'Train type',
    Deluxe: 'Deluxe',
    CarCategory: 'Car category',
    TrainDepartureDate: 'Departure date',
    TrainDepartureTime: 'Departure time',
    TrainArrivalTime: 'Arrival time',
    TrainRunTime: 'Travel time',
    DeluxeTrain: 'Deluxe train',
    Train: 'Train',
    deluxe: 'deluxe',
    passengerTrain: 'passenger',
    fast: 'fast',
    rapid: 'rapid',
    TrainDeparture: 'Departure',
    TrainArrival: 'Arrival',
    PlasticPaymentTextConvertation: 'Payment will be&nbsp;processed by&nbsp;the airline directly using it&rsquo;s native currency and therefore we&nbsp;ask you to&nbsp;understand that the amount specified above may differ from that charged to&nbsp;your credit card due to&nbsp;exchange rate fluctuations and possible currency conversion.',
    Station: 'Station',
    TrainStop: 'Stop',
    MinimalCost: 'Minimum cost for one adult passenger in',
    lowerCompartmentSeatsCount: 'lower compartment seats',
    upperCompartmentSeatsCount: 'upper compartment seats',
    lowerSideSeatsCount: 'lower side seats',
    upperSideSeatsCount: 'upper side seats',
    maleSeatsCount: 'male seats',
    femaleSeatsCount: 'female seats',
    mixedSeatsCount: 'mixed seats',
    otherSeatsCount: 'uncategorized seats',
    compartmentsCount: 'entire compartments',
    totalSeatsCount: 'total',
    seatsCount: 'seats',
    NotAllJourneys: 'Not all flights are shown. If none of them are suitable, <a href="/en/railways/booking/">refine search options</a>.',
    Copy: 'Copy',
    BookmarkAndShare: 'Share or bookmark',
    CouldnotConfirmTrain: 'Unfortunately we could not confirm available seats on the chosen train. Please choose a different train or try again in 15 minutes.',
    compartmentComplete: 'Whole compartment only',
    maleCompartment: 'Male compartment',
    femaleCompartment: 'Female compartment',
    lower: 'Lower',
    upper: 'Upper',
    seat: 'seat',
    seats: 'Seats',
    number: 'number',
    ShowJourneyDetailedInfo: 'Show detailed information about the journey',
    SelectOnTrainCarScheme: 'Select seats on the scheme for all passengers',
    N: 'n.',
    Car: 'Car',
    SelectSeat: 'Select a seat',
    ConfirmChoice: 'Confirm choice',
    MinimalCost: 'Minimum cost for one adult passenger',
    CallFromComputer: 'Call from your computer',
    AexInfo: 'High-speed train connecting Moscow with airports.',
    ShowMore: '<a class="show" target="_blank" href="{0}">Read more</a>',
    AexIsNonRefundable: 'Aeroexpress tickets are nonrefundable (see <a class="show" target="_blank" href="http://www.aeroexpress.ru/en/forPassengers/rules.htm">The regulations of passenger transportation, paragraph 2.7</a>).',
    AexTickets: 'Aeroexpress tickets',
    EMD: 'Electronic miscellaneous document',
    GetAexTickets: 'Download Aeroexpress tickets',
    PrintAexTickets: 'Please click the "Download Aeroexpress tickets" button below. Print the tickets and keep them close at hand to pass through the turnstiles at the airport, or present them to a controller if requested.',
    AboutSiteRailway: '<p>Agent.ru provides booking of railway tickets online. Choosing a ride, you can see its price and can make an informed choice. We offer tickets that can be paid for by a bank card, with Yandex.Money, with WebMoney, with cash using any payment system or at Russian Post offices.</p><p>If it is the first time that you book airline tickets online and have any difficulties, contact our support service.</p>',
    AboutSiteHotels: '<p>Agent.ru allows guests to book hotel rooms online. All the accomodation options include the final price so that you can make an informed choice. Payments are made directly on the website of the hotel of your choice by credit card, or through many other supported payment systems.</p><p>If this is the first time you book hotel rooms online, contact our support service.</p>',
    RailwayMainText: 'Shopping for railway e-tickets online is very easy and convenient! The entire procedure takes only a few minutes. You can explore railway schedules for the desired route and travel date, choose a specific train, carriage type and service class and any of the free seats available at the moment. Purchased tickets are available at all Russian Railways ticketing offices, UFS registration stands and self-service terminals. Online check-in is also available. All financial transactions are secured by the latest achievements in information protection technology, which assures your safety during purchase.',
    PromoCode: 'Promo code',
    PromoCodeIfExist: 'Промо-код, если есть',
    PromoCodeTip: 'Информацию о том, как получить промокод,<br /> можно найти <noindex><a href="http://goo.gl/zmn9O" target="_blank" class="show" rel="nofollow">на&nbsp;нашей странице в&nbsp;Facebook</a></noindex>!',
    PromoCodeMessage: 'Incorrect code. Please make sure you have entered the right code and try again.',
    DocumentsForTravel: 'Travel documents',
    PrintDocumentsForTravel: 'Print the documents needed for your trip',
    BonusCardInfo: "Please note that some airlines require the passenger's name to match that of the frequent flyer card's owner. For more details please refer to the web-site of the chosen aircompany.",
    Where: 'Where',
    CheckInDate: 'Check-in',
    CheckOutDate: 'Check-out',
    Guests: 'Adults',
    Rooms: 'Rooms',
    FindHotels: 'Find hotels',
    ImportantlyBlockRailwayFirst: '<li>Agent.ru offers only electronic tickets.</li><li>If&nbsp;you are accompanied by&nbsp;children under 5 years, booking a&nbsp;separate seat for the child is&nbsp;not allowed. Every child must be&nbsp;accompanied by&nbsp;an&nbsp;adult. Tickets for children of&nbsp;5 to&nbsp;10 years old are available at&nbsp;reduced fares. If&nbsp;your child turns 10 during your trip, adult fare is&nbsp;required.</li>',
    ImportantlyBlockRailwaySecond: '<li>Railway <nobr>e-ticket</nobr> is&nbsp;very handy as&nbsp;you can complete your purchase without leaving your home or&nbsp;office. When using online <nobr>check-in</nobr> you will only need your passport to&nbsp;board the train! If&nbsp;you decide not to&nbsp;<nobr>check-in</nobr> online you will have to&nbsp;exchange your order receipt to&nbsp;a&nbsp;Russian Railways ticket at&nbsp;any ticketing office, UFS registration stand or&nbsp;<nobr>self-service</nobr> terminal. The electronic ticket can be&nbsp;paid for with <noindex><a href="https://money.yandex.ru/" rel="nofollow" class="show">Yandex. Money</a></noindex>, with <noindex><a href="http://www.webmoney.ru/" rel="nofollow" class="show">WebMoney</a></noindex>, with cash in&nbsp;any Russian Post office or&nbsp;any supported payment system: <noindex><a href="http://www.qiwi.ru/" rel="nofollow" class="show">QIWI</a></noindex>, <noindex><a href="http://euroset.ru/" rel="nofollow" class="show">Euroset</a></noindex>, <noindex><a href="http://freecash.ru/" rel="nofollow" class="show">Svobodnaya kassa</a></noindex>, <noindex><a href="http://elecsnet.ru/" rel="nofollow" class="show">Elecsnet</a></noindex>, or&nbsp;by&nbsp;a&nbsp;Visa or&nbsp;Mastercard bank card.</li><li>The time shown in&nbsp;the search results (as&nbsp;well as&nbsp;in&nbsp;your ticket) is&nbsp;local, i.e. the time of&nbsp;the city of&nbsp;departure or&nbsp;arrival, respectively.</li><li>Search results can be&nbsp;filtered by&nbsp;departure time, arrival time, travel time or&nbsp;price by&nbsp;clicking the heading of&nbsp;the appropriate column.</li><li>You can see complete information about the train route by&nbsp;clicking on&nbsp;the train number you are interested in.</li><li>For details on&nbsp;refunding your ticket or&nbsp;changing the flight date for the selected fare, refer to&nbsp;the <noindex><a href="http://ufs-online.ru/help/default.aspx?f=eticket.rules" rel="nofollow" class="show">Russian Railways ticket refund rules</a></noindex> (Russian).</li>',
    ImportantlyBlockRailwayThird: "<li>To complete your booking you will be redirected to the JSC UFS website, where you'll be able to enter your passenger data, payment details and check in online.</li>",
    TrainsNotFound: 'There are no trains or no available seats available for your search. Please try changing your search criteria.',
    WaitWeAreCheckingAvailabilityTrains: 'Please wait while we confirm seat availability on the chosen train.',
    AcceptThePrice: 'You will be able to choose a payment method upon completing your order.',
    unavailable: 'unavailable',
    AdditionalServices: 'Additional services',
    Vacancies: 'Jobs',
    SimPromoText: '<dl><dt>Save money on roaming!</dt><dd>International sim-cards<br /> with 10$ on balance for 500 rubles!</dd></dl>',
    DirectFlightsOnlyHint: 'Try not restricting your search to&nbsp;direct flights only&nbsp;&mdash; you may find some suitable flights with stops.',
    BookingClassHint: 'Try choosing a different booking class&nbsp;&mdash; there might be no seats available for the specified class.',
    MoreLandingTickets: 'Each passenger will receive {0} ticket(s). Please contact {1} on whether it will be necessary to leave the airport transit zone during the connection. In that case, you might have to obtain a visa of the country hosting the connection, and also claim your luggage and pass through customs and immigration control.',
    SavePersonalDataSuccess: 'Your personal data was successfully changed.',
    ContractsConditions: 'Contracts and conditions',
    ContractsConditionsList: '<a title="Show the terms of exchange and refund of these tickets" href="#" class="popupLink showFareRules">Terms of exchange and refund of tickets</a><br /><a class="show" target="_blank" href="{0}">Transportation conditions</a><br /><a class="show" target="_blank" href="/en/help/laws/oferta/"><nobr>Contract-offer</nobr></a>',
    ContractsConditionsList1: '<a title="Show the terms of exchange and refund of these tickets" href="#" class="popupLink showFareRules">terms of exchange and refund of tickets</a>,<br />',
    ContractsConditionsList2: '<a class="show" target="_blank" href="{0}">transportation conditions</a> and <a class="show" target="_blank" href="/en/help/laws/oferta/"><nobr>contract-offer</nobr></a>',
    CarRental: 'Car rental',
    CarRentalHeader: 'Car rental',
    Cars: 'Cars',
    differentDropOff: 'different drop off',
    Pickup: 'Pick up',
    DropOff: 'Drop off',
    DropOffDate: 'Drop off date',
    PickUpDate: 'Pick up date',
    DriverDetails: 'Driver details',
    DriversAge: "Driver's age",
    Blog: 'Blog',
    LocationHintMessage: 'Please select specific rental office',
    AlfaInfo: '<sup class="dash">&mdash;</sup>Combined insurance policy covering life and health risks during flight, and health insurance for the duration of your stay in any country of the world. <a class="show" target="_blank" href="/en/additional-services/#alfa-strahovanie">See more</a>',
    AlfaAdvertising: 'Combined insurance policy covering life and health risks during flight, and health insurance for the duration of your stay in any country of the world.',
    InsuranceForFlight: 'In-flight insurance',
    InsurancePolicy: 'Insurance policy',
    AlfaRefundInfo: 'Please note that in case you return a ticket before any of the flight segments were used, a 100% refund for the insurance policy will be made automatically when you request the return. Upon termination of&nbsp;the insurance contract concluded for a&nbsp;return trip after the start of&nbsp;the first segment, the insurance premium is&nbsp;<nobr>non-refundable</nobr>.',
    OfficeAerovokzal: 'Central office',
    OfficeLeninsky: 'Office at Leninsky',
    Reports: 'Reports',
    LowCostNotRefund: 'Unfortunately, low-cost airline tickets are <a href="/en/help/laws/low-costs/">non-refundable</a>.',
    Taxi: 'Taxi',
    TaxiAdvertising: 'A comfortable cab with a fixed rate within Moscow limits will take you to the airport in time for departure and anywhere in Moscow on arrival.',
    TaxiInfo: '<sup class="dash">&mdash;</sup>Taxi fare to or from the airport within Moscow limits is 1,000 rubles. You will be contacted after you purchase your tickets and 5 hours before the ride.',
    taxiPayment: 'paid on the spot',
    'error.password.wrong.current': 'You have entered a wrong old password, so we cannot change it for the new one. Make sure the Caps Lock key is not pressed or use the password reminder function.',
    'exception.bonus_card.aircompany_already_exist': 'The card number for the selected bonus program is already specified for this passenger.',
    'error.booking.variant.unableSelect': 'Error selecting an option.',
    'error.booking.variant.notSelected': 'No option is selected.',
    'error.booking.variant.invalidCityName': 'City not found.',
    'error.booking.fareInfo.gettingError': 'Could not obtain tariff application conditions',
    'error.booking.doBooking': 'Unfortunately, the airline does not confirm the opportunity to book a ticket for the selected flight right now. Please, choose another flight or try again later.',
    'error.booking.blocked': 'You have run out of the maximum number of corrections for a single booking session. Please, make up your mind about your search criteria beforehand and try again.',
    'error.booking.noBookingResult': 'No booking results found',
    'error.booking.confirm': 'Could not confirm the booking',
    'error.booking.passengerNotUnique': 'A passenger with such data already exists.',
    'error.authentication.quick.badLogin': 'Wrong login',
    'error.authentication.quick.badPassword': 'Wrong password',
    'error.authentication.quick.DBError': 'Connection error',
    'error.registration.clientAlreadyExist': 'A client with this email address already exists.',
    'error.email.change.alreadyExists': 'A user with this email address is already registered in the system.',
    'error.booking.cancel': 'Error connecting to the automated booking system. Please, wait for 15 minutes and try again.',
    'info.booking.variant.cityMultiplication': 'Please, reenter the city. There are more than one airport that correspond your search, and we are not sure we can make right choice without your help.',
    'info.booking.variant.invalidSearchParams': 'Illegal search parameters.',
    'info.booking.variant.cityDuplication': 'Apparently you are attempting to book a round-the-world trip. Unfortunately such trips are not yet available, please choose a different destination :)',
    'info.booking.variant.notFound': 'If you cannot find a two way trip, try booking two separate flights. The reservations system does not return any variants unless both directions meet all search criteria including available seats and flights.',
    'info.booking.airport.svo': "Please contact your aircompany or airport's help desk in advance to find out which Sheremetyevo terminal hosts your flight.",
    'error.payment': 'There was an error while redirecting you to the payment system. Please try again in 15 minutes. If the problem persists, contact our customer service.',
    'error.payment.is.not.registered': 'The specified type of payment is not registered in the order.',
    'payment.reprice': 'The total cost of your order has been changed by the airline, probably because too much time had passed since booking. We have automatically updated the order&nbsp;&mdash; please verify your data and retry payment.',
    'error.password.change.badEmail': 'There is no user with the specified email address.',
    'error.password.change.sending': 'Could not send the email. Try again.',
    'error.password.change.badClient': 'No such client exists. Make sure the link is correct and try again.',
    'info.password.change.emailSent': 'A letter has been sent to the email address you specified during registration. To change your password, click the link in that letter. If you don’t remember the email address you specified, contact our around-the-clock support service and our operators will tell it to you.',
    'info.password.change.successful': 'Your password has been changed successfully.',
    'error.authentication.quick.badCredantials': 'You have entered a wrong email address or password. Make sure the Caps Lock key is not pressed.',
    'info.booking.orderComplete': 'You have made your order successfully',
    'info.estimated.total.not.equal.to.result': 'Booking flight tickets at the selected price is prohibited by the airline at the moment. For your convenience we have found the closest tariff at which you can continue to book the selected flight. If the tariff does not satisfy you for some reason, please consider other flight options.',
    'info.refund.submitted': 'Refund information submitted.',
    'error.feedback': 'Unable to send feedback',
    'error.feedback.attachments': 'Unable to send feedback. Total fiel size restriction is 20MB',
    'error.sserver': 'Server error. Reload the page and try again.',
    'error.booking.passenger.document.expiresBeforeFlight': 'The passenger’s document expires before the transfer.',
    'error.profile.notComplete': 'To access the rest of the My Orders section, you must fill in the fields of this form. We only need basic information in order to understand you better and keep in touch with you.',
    'error.validation.email': 'Invalid email address format. The field must contain an email address in the format: user@domain.com.',
    'error.order.doesNotExist': 'Order with such pnr and passenger name does not exist',
    'info.aircompany.flight.not.found': 'Unfortunately, the flight you have chosen is not available for booking at this moment. Please take a look at other flight options from the list below&nbsp;&mdash; one of them might meet your requirements.',
    'info.payment.priceRestriction': 'In accordance with Federal Law № 103 of the payment amount in Euroset may not exceed 14 999 rubles, so if the amount of your order prevycit this restriction, you must use another method of payment.',
    'info.payment.waitingForCategoryConfirmation': "At the moment the order to be confirmed by the airline. Please contact the operator of our round-the-clock service support, to know when you'll be able to continue to checkout.",
    'info.payment.waitingForConfirmation': "At the moment the order to be confirmed by the airline. This process usually takes no more than 10 minutes, but if your anticipation will last longer, we will further notify you by e-mail about the possibility to continue your order.",
    'error.client.delete.pendingOrders': 'I can not remove. Remained orders requiring intervention.',
    'info.timetable.city_not_found': 'Unfortunately, you specify the city did not match any airport from our database. Please try to enter the name again, using the AutoCorrect feature, or contact our customer support around the clock to understand the reasons for discrepancies.',
    'error.booking.accompaniedChildren': 'Unfortunately you have entered incorrect information about the order of the accompanying adult. Please enter the order number as it appears in the itinerary receipt and the name of the passenger-leader. If the ticket was purchased on the site agent.ru, correct data can also be found in the section "My orders" for detailed information on the Related Order.',
    'error.checking.booking.availability.failed': 'Unfortunately, the airline has not confirmed the possibility of your ticket on the flight of your choice at a specified earlier rate, and find other trip we did not. Try changing your search or search again later.',
    'error.invalid.captcha.result': 'Wrong CAPTCHA. Try again.',
    'error.schedule.unableToGet': 'Unfortunately the schedule server is currently unavailable, please try again in a few minutes. If the problem persists, please contact our 24/7 Customer Support service.',
    'error.refund': 'Unfortunately, we were not able to register your request. Please try again in case of recurrence of this error please report the problem to Customer Service so that we can take prompt action to address it.',
    'error.attachments.refund': 'Failed to request a refund for the ticket. The size of the ticket can not exceed 3MB.',
    'error.info.refund': 'Unable to get information on Cancellations',
    'error.refund.non.agency.on.agency.refund': 'Заказ был оформлен клиентом непосредственно на сайте agent.ru, поэтому возврат денежных средств по нему в вашем агентстве невозможен. Пожалуйста, сообщите клиенту о необходимости самостоятельно заполнить заявление на сайте.',
    'error.state.refund': 'Unable return order. Order is not complete.',
    'error.session.expired': 'Your session has expired due to inactivity. Please log in or enter order data to continue.',
    'info.booking.updated': 'Unfortunately, the airline has changed the departure time of one or more flights. Please check the updated data, and if they do not suit you, look at other flight variants.',
    'error.promo': 'Error while promo retrieval',
    'error.bonusCards.form.notComplete': 'All fields of this form are required. Please check your entries again.',
    'info.booking.variant.tooManyPassengers': 'Unfortunately, you chose does not allow the airline ticketing more than 3 passengers. Please <a class="black" href="/en/booking/">take a few separate orders</a> with fewer passengers, or choose another airline.',
    'info.session.expired': 'Unfortunately, the results may become obsolete, so we recommend you start the booking process from the beginning.',
    'error.aex.booking': 'Unfortunately we could not book your Aeroexpress tickets. Please try confirming your order again in a few minutes, or book the tickets through <a target="_blank" href="http://www.aeroexpress.ru">www.aeroexpress.ru</a>.',
    'error.booking.variant.no': 'No variants',
    'info.booking.bonusCard.invalid': 'Unfortunately, one of the frequent flyer card numbers you have entered is incorrect or not eligible for the chosen flights. Please go back to Step 4 and verify the data, or contact the aircompany for details.',
    'info.railway.journey.notFound': 'There are no trains or no available seats available for your search. Please try changing your search criteria.',
    'info.booking.variant.directFlightsNotFound': 'Unfortunately, the flights you have chosen are not available for booking at this moment. Please take a look at other flight options from the list below&nbsp;&mdash; one of them might meet your requirements.',
    'info.booking.variant.obsolete': 'Unfortunately, the results may become obsolete, so we recommend you start the booking process from the beginning.',
    'info.order.errorMistary33043': 'According to airline regulations the order cannot be cancelled within 15 minutes of its creation. Please try again later.',
    'info.order.successfullyRegistration': 'You are successfully registered. You may always update your information at the "<a href="/en/personal/profile/">Personal Data</a>" and "<a href="/en/personal/password/">Account Settings</a>" pages of our site. If you have never booked a ticket at Agent.ru before, please check out the step-by-step instructions in the "<a href="/en/help/reservation/">How to Book</a>" section. If you experience any difficulties booking tickets, feel free to contact our Customer Support Service.',
    'info.booking.sequence': 'Unfortunately the booking procedure has been interrupted. Please make sure that www.agent.ru is not opened in several tabs or windows of your browser simultaneously and try again.',
    'error.order.refund.wordOrderError': 'Sorry. Ticket is not refunded, because code word is wrong.',
    'error.blog': 'Sorry, blog is unavailable right now.',
    'error.routeTicket': 'Sorry, but route ticket is unavailable right now',
    'error.insuranceReceipt': 'Sorry, but insurance is unavailable right now',
    'error.insurance.creation': 'Unfortunately we were unable to confirm insurance for the passengers you have indicated. Please try again or contact the customer support service should the problem persist.',
    'error.railway.passengers': 'Can not save passengers',
    'error.railway.passengers.nameTooLong': "According to railroad ticketing rules the combined length of a passenger's first and last names must not exceed 40 symbols. Please replace the first name with its initial letter or remove any secondary parts of the last name.",
    'error.taxi.booking': 'Unalbe to order taxi.',
    'error.authentication.agency.timeout': 'Unfortunately we could not log you in due to technical reasons, please try again in a few minutes. If the problem persists contact our Customer support service.',
    'error.enter.real.first.name': 'Please enter your real given name',
    'error.enter.real.last.name': 'Please enter your real family name'
  }
});
